### PR TITLE
Handle special characters in user names

### LINKED ISSUE #53: Jupyterhub kernel access no longer works for users with certain special characters in their username
With newer `vscode-jupyter` extension versions than `v2023.9.1102792234`, it is no longer possible to access / use Jupyterhub kernels for Jupyterhub users with special characters in their username like `user (test)`.

Its the same issue somebody raised in [issue 15055](https://github.com/microsoft/vscode-jupyter/issues/15055) as far as i can see but this one was closed. 

This issue is also not in the separate `ms-toolsai.jupyter-hub` extension. The authentication works fine but the subsequent kernel iteration through `vscode-jupyter` breaks.

## Environment data

-   VS Code version: Version: 1.87.2
-   Jupyter Extension version (available under the Extensions sidebar): everything greater than `v2023.9.1102792234` e.g. `v2024.2.0`
-   Python Extension version (available under the Extensions sidebar): v2024.2.1
-   OS (Windows | Mac | Linux distro) and version: Linux Ubuntu
-   Python and/or Anaconda version: 3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda/mamba
-   Jupyter server running: Tested on a Local and Remote Jupyterhub instance (docker setup).
  - One for the bug potential import config detail is that we use the [separate proxy setup](https://jupyterhub.readthedocs.io/en/stable/howto/separate-proxy.html).

## Expected behaviour

The specific Jupyterhub user can login via the web ui and their server instance is started.
They then can use the Jupyterhub Server URL, username and generated token to setup a new Jupyterhub connection to access and use the kernels there in VSCode.  Finally they can use one of the shown kernels to execute a example Notebook.

This also works if one uses `vscode-jupyter` extension versions `v2023.9.1102792234`.

## Actual behaviour

The specific Jupyterhub user can login via the web ui and their server instance is started.
They then can use the Jupyterhub Server URL, username and generated token to setup a new Jupyterhub connection to access and use the kernels there in VSCode.

Get an error `Cant connect to Remoteserver` after the Jupyterhub connection setup is complete and i cant see any kernels from the remote server to use. You can find the complete Extension Output at the bottom.

The relevant line from the output is `http://localhost:8000/user/user%20(test)/api/kernels?1711536811205`. What works and what the Jupyterhub expects is `http://localhost:8000/user/user%20%28test%29/api/kernels?1711536811205`.

I am unsure if the error is only due to our use of the [Jupyterhub separate proxy deployment](https://jupyterhub.readthedocs.io/en/stable/howto/separate-proxy.html) or if the Jupyterhub internal proxy also has this issue, but it is very likely. 

The fact is that jupyterhub encodes every special character except `~` and `@` for the username and expects the username to be encoded in request paths like that. This can partially be seen [here](https://github.com/jupyterhub/jupyterhub/blob/main/jupyterhub/user.py#L526) and [here](https://github.com/jupyterhub/jupyterhub/blob/f0220c87d83b3e16a11733102291200ce99bb4e7/jupyterhub/utils.py#L455). For some background behind this behaviour i found also [this issue](https://github.com/jupyterhub/jupyterhub/issues/1717) which talks about it.

Basically what happens then is, that the Jupyterhub proxy knows to redirect a request for `http://localhost:8000/user/user%20%28test%29/` but not for `http://localhost:8000/user/user%20(test)/`. That is why we see the 404 error in the log output.

My best guess is you broke this with https://github.com/microsoft/vscode-jupyter/commit/4b47894e51122f1552803df87aef5043ce6a3a07 by no longer encoding some characters in the whole base url which also contains the username. But i think it was also not fully consistent with how Jupyterhub expects everything to be encoded before.

Also as far as i could see the `vscode-jupyterhub` extension is not affected by this issue because they retrieve the user info `server` property from the Jupyterhub server and build the server user instance url by appending it to the base url as can be seen [here](https://github.com/microsoft/vscode-jupyter-hub/blob/main/src/jupyterHubApi.ts#L176C9-L176C61) (At least in the happy path where the Jupyter server returns the `server` property for the user. The fallback implementation looks buggy). The Jupyterhub user info `server` property contains the correctly encoded username.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Setup or use a local or remote Jupyterhub instance. Login in and start the server with a user called `user (test)`. This is quite easy to simulate with the `DummyAuthenticator` authenticator module which allows any kind of username to be tested.

2. Setup a API Tokens for authentication on the Jupyterhub instance

3. Use the url, user name and token and create a new remote Jupyterhub connection

    1. Select `existing Jupyterhub-Server`
    2. Select `enter URL for existing Server`
    3. Enter URL for Jupyterhub server. In my local example `http://localhost:8000`
    4. Enter Username for Jupyterhub server instance. In my local example `user (test)`
    5. Enter previously generated Jupyterhub server instance token as Password.
    6. Enter a name under which Vscode saves the Jupyterhub server. In my local example `JupyterHub (test)`
    7. Get the error `Cant connect to Remoteserver`. See also the image (its in german though)
      jupyter_extension error
   8. The Jupyterhub connection details are saved but every time i try to access it via VSCode  i get the above error.

 

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
11:53:31.116 [info] Start refreshing Kernel Picker (1711536811116)
11:53:31.211 [error] Error fetching kernels from http://localhost:8000/user/user (test)/ (JupyterHub (test)): [r [Error]: Invalid response: 404 Not Found
	at r.create (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:1067)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Object.Rl [as listRunning] (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:4507)
	at async r.getRunningKernels (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:198:12975)
	at async Promise.all (index 0)
	at async sD.listKernelsFromConnection (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:308:19197)
	at async ~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:308:17485] {
  response: p [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'http://localhost:8000/user/user%20(test)/api/kernels?1711536811205',
      status: 404,
      statusText: 'Not Found',
      headers: [p [Headers]],
      counter: 0
    }
  },
  traceback: ''
}
11:53:31.213 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache [r [Error]: Invalid response: 404 Not Found
	at r.create (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:1067)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Object.Rl [as listRunning] (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:4507)
	at async r.getRunningKernels (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:198:12975)
	at async Promise.all (index 0)
	at async sD.listKernelsFromConnection (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:308:19197)
	at async ~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:308:17485] {
  response: p [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'http://localhost:8000/user/user%20(test)/api/kernels?1711536811205',
      status: 404,
      statusText: 'Not Found',
      headers: [p [Headers]],
      counter: 0
    }
  },
  traceback: '',
  vslsStack: [
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {}
  ]
}
11:53:31.214 [error] Jupyter Lab Helper:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at v.dispose (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:10935)
	at ni.dispose (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:29299)
	at r.dispose (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:198:12579)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)
	at async sD.listKernelsFromConnection (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:308:20060)
	at async ~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:308:17485]
11:53:31.237 [info] End refreshing Kernel Picker (1711536811116)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #53

### CODE REVIEW

File: src/jupyterIntegration.ts [hunk 1]
```diff
@@ -223,21 +225,53 @@ export class JupyterServerIntegration implements JupyterServerProvider, JupyterS
...
+        const rawBaseUrl = await getUserJupyterUrl(
+            serverInfo.baseUrl,
+            authInfo.username || '',
+            authInfo.token,
+            this.fetch,
+            cancelToken
         );
+        // https://github.com/microsoft/vscode-jupyter-hub/issues/53
+        // baseUrl = baseUrl.replace(/%40/g, '@').replace(/%7E/g, '~');
+        const baseUrl = Uri.parse(rawBaseUrl);
```
Comment (amunger) [inline src/jupyterIntegration.ts:237]: A set of unit tests might help explain what is expected to happen here. This is pretty difficult to know what's going on here.

**Review by amunger — APPROVED** [review]

File: src/jupyterIntegration.ts (hunk 1 above)
Comment (DonJayamanne) [reply src/jupyterIntegration.ts:237]: Agreed

**Review by mjbvz — APPROVED** [review]
